# Generated by Django 5.0.6 on 2024-07-05 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('book', models.CharField(choices=[('qaidah', 'Qaidah'), ('quran_reading', 'Quran Reading'), ('hifz', 'Hifz'), ('na', 'N/A')], default='na', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('admin_teacher', 'Admin Teacher'), ('regular_teacher', 'Regular Teacher'), ('student', 'Student'), ('waiting_list', 'Waiting List')], default='waiting_list', max_length=20)),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('punctuality', models.FloatField(blank=True, null=True)),
                ('class_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.classname')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='classname',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user_type__in': ['admin_teacher', 'regular_teacher']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.profile'),
        ),
    ]
