# Generated by Django 5.0.6 on 2024-07-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='attendance',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='punctuality',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
