# Generated by Django 5.0.6 on 2024-07-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_attendance_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
