# Generated by Django 5.0.6 on 2024-07-06 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_attendance_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
