# Generated by Django 5.0.6 on 2024-07-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_classname_options_alter_profile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='attendance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='punctuality',
        ),
    ]
