# Generated by Django 5.0.6 on 2024-07-09 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
