# Generated by Django 5.0.6 on 2024-07-09 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_classname_options_alter_profile_options'),
        ('attendance', '0002_alter_attendance_reason'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('profile', 'date'), name='unique_attendance_record'),
        ),
    ]
