# Generated by Django 5.0.6 on 2024-07-09 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_classname_options_alter_profile_options'),
        ('attendance', '0003_attendance_unique_attendance_record'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='attendance',
            name='unique_attendance_record',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('profile', 'date')},
        ),
    ]
