# Generated by Django 5.0.6 on 2024-07-10 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_profile_attendance_remove_profile_punctuality'),
        ('attendance', '0004_remove_attendance_unique_attendance_record_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('profile', 'date'), name='unique_profile'),
        ),
    ]
